modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="broken_smp_god_shards"
version="1.0.0"
displayName="broken_smp_god_shards"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="jackh, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.broken_smp_god_shards]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.broken_smp_god_shards]]
    modId="mcreator_link"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.broken_smp_god_shards]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration